// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgqddlasjyihjprpbhky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncWRkbGFzanlpaGpwcnBiaGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTQ5NjUsImV4cCI6MjA2ODA3MDk2NX0.1e_PvLBDMNnLJhNEeGz3_NEkL_V2X2AgqrV9pgokb3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});